### PR TITLE
Update software-has-a-purpose.html

### PR DESCRIPTION
**Pull request by asottile**
<3

### CODE REVIEW

**Comment by imbstack** [comment]
Gah, how do I Github?

<3 :+1: 

miss you too :p

**Comment by asottile** [comment]
If you're around we should grab a drink some time

**Comment by imbstack** [comment]
@asottile I'm in Pittsburgh for the time being (Pittsburgh+-). I'll hopefully be back in the bay at least for a visit in the next month or so and I'll let you know for sure.

**Comment by asottile** [comment]
Sounds good!  Hope you're feeling well, friend.

**Pull request merged**
